title: Developer Ramblings of Kevin Smith
description: >
  Developer Ramblings of Kevin Smith
#permalink: ':title/'
baseurl: ""
url: ""
site-twitter: kev_bite
site-img: site-image.png
author: Kevin Smith
author-img: kevin-smith.png
about-author: |
  [Microsoft MVP](https://mvp.microsoft.com/en-us/PublicProfile/5003489),
  Developer,
  technology enthusiast
  and [@dotnetsheff](https://dotnetsheff.co.uk)/[@dotnetYork](https://dotnetYork.co.uk) organiser.
social-twitter: kev_bite
social-facebook:
social-github: kevbite
social-linkedin: kevbite
social-email: kev_bite@msn.com

discus-identifier: kevsoft

analytics:
google_tag_manager: GTM-5N8RNG

highlighter: rouge
markdown: kramdown


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

collections:
  events:
    output: true